### ISSUE TITLE
[Meta] Schema deployment problems - Stuck with Applying Changes

### ISSUE THREAD

**Issue by marktani** [graphcool/graphcool#1425]
* [x] https://github.com/graphcool/framework/issues/1420 
* [x] https://github.com/graphcool/framework/issues/1426
* [x] https://github.com/graphcool/framework/issues/1436
* [x] https://github.com/graphcool/framework/issues/1466
* [x] https://github.com/graphcool/framework/issues/1490
* [x] https://github.com/graphcool/framework/issues/1532

**Comment by dpetrick** [comment]
All fixed in PR #1558

**Comment by marktani** [comment]
This was fixed [in the release candidate for Graphcool 1.0](https://github.com/graphcool/graphcool/pull/1318#issuecomment-356417351).
